version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: doxology_postgres
    restart: always
    environment:
      POSTGRES_USER: doxology
      POSTGRES_PASSWORD: doxology
      POSTGRES_DB: doxology_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
